framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    session:
        handler_id: snc_redis.session.handler
        cookie_lifetime: 86400

    php_errors:
        log: true

    assets: ~

    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_HOST)%/4"

    templating:
        engines:
            - 'twig'

    validation:
        enable_annotations: true

    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
        enabled: true

    router:
        strict_requirements: true
