nelmio_api_doc:
    documentation:
        info:
            title: KodeCMS
            description: Symfony 4 CMS
            version: 0.0.1-dev
    areas:
        path_patterns:
            - ^/api(?!/doc|doc.json$)
