nelmio_api_doc:
    documentation:
        info:
            title: KodeCMS
            description: Symfony 4 CMS
            version: "%env(resolve:VERSION)%"
    areas:
        path_patterns:
            - ^/api(?!/doc|doc.json$)
