app.swagger:
    path: /api/doc.json
    methods: GET
    options:
        i18n: false
    defaults:
        _controller: nelmio_api_doc.controller.swagger

app.swagger_ui:
    path: /api/doc
    methods: GET
    options:
        i18n: false
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui
