services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EasyCorp\EasyLog\EasyLogHandler:
        public: false
        arguments:
            - '%kernel.logs_dir%/%kernel.environment%.log'

    redis.result_cache.provider:
        class: Doctrine\Common\Cache\PredisCache
        arguments:
            - '@snc_redis.cache_client'
